<?php 
$customer = Mage::getSingleton('customer/session')->getCustomer();
$customerId = $customer->getId();
$customerEntityId = $this->helper('accolade_bttn')->getCustomerEntity($customerId)[0]; 
$customerShippingData = Mage::getModel('customer/address')->load($customer->default_shipping)->getData();
$customerAddress = $customerShippingData['street'];
$customerCountryCode = $customerShippingData['country_id'];
$customerPostCode = $customerShippingData['postcode'];
?>
<div class="page-title">
	<h1><?php echo $this->__('My Bt.tn') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php if($customerEntityId): echo $this->getUrl('*/*/save/id/'.$customerEntityId.'/'); else: echo $this->getUrl('*/*/create/id/'.$customerId.'/'); endif; ?>" id="form" method="post" name="form">
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <ol>
		<h2><?php echo $this->__('My Bt.tn Details') ?></h2>
			<li class="item">
			<br /><br />
			<?php
			//# display button ID
			$bttnInfoArr = $this->helper('accolade_bttn')->getBttnInfo($customerId)[0]; 
			if(!$bttnInfoArr['button_id']){
				echo $this->__('Button ID: None').'<br>';
			} else {
				echo $this->__('Button ID: ').$bttnInfoArr['button_id'].'<br>';
			}
			
			//# display current shipping method
			$cart = Mage::getSingleton('checkout/cart');
			$address = $cart->getQuote()->getShippingAddress();
			$address->setCountryId($customerCountryCode)
					->setPostcode($customerPostCode)
					->setCollectShippingrates(true);
			$rates = $address->collectShippingRates()->getGroupedAllShippingRates();
			foreach ($rates as $carrier) {
				foreach ($carrier as $rate) {
					if ($bttnInfoArr['shipping_method'] == $rate->getData()['code'])
					{
						$shippingTitle = $rate->getData()['method_title'];
						break;
					}
				}
			}
			if(!$shippingTitle){
				echo $this->__('Shipping Method: None').'<br>';
			} else {
				echo $this->__('Shipping Method: ').$shippingTitle.'<br>';
			}
			
			//# display current payment method
			$payments = Mage::getSingleton('payment/config')->getActiveMethods();
			foreach ($payments as $paymentCode=>$paymentModel) {
				$_title = Mage::getStoreConfig('payment/'.$paymentCode.'/title');
				if ($paymentCode == $bttnInfoArr['payment_method'])
				{
					$paymentTitle = $_title;
					break;
				}
			}
			if(!$paymentTitle){
				echo $this->__('Payment Method: None').'<br/>';
			} else {
				echo $this->__('Payment Method: ').$paymentTitle;
			}
			
			//# display test URL
			if($bttnInfoArr['button_id']){
				$testURL = Mage::getBaseUrl().'accoladebttn/index?bid='.$bttnInfoArr['button_id'];
				echo '<br/><br/><a href='.$testURL.'>Test URL</a>';
			}
			?>
			<br /><br /><br />
            </li>
        </ol>
    </div>

    <div class="col-2 addresses-primary">
        <ol>
		<h2><?php echo $this->__('Edit Bt.tn Details') ?></h2>
            <li class="item">
                <div class="fieldset">
					<ul class="form-list">
						<li>
							<label for="button_id"><?php echo $this->__('Add Bt.tn device ID') ?></label>
							<div class="input-box">
								<input type="text" name="button_id" alt="button_id" id="button_id" class="input-text" value="<?php if($bttnInfoArr['button_id'])echo $bttnInfoArr['button_id']; ?>" />
							</div>
						</li>
					</ul>
				</div>
            </li>
        </ol>
    </div>
</div>

<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <ol>
		<h2><?php echo $this->__('Shipping Method') ?></h2>
			<li class="item">
                <div class="fieldset">
					<ul class="form-list">
						<li>
							<label for="button_id"><?php echo $this->__('Choose default shipping method:') ?></label>
							<br/>
							<?php 
							if($customerAddress !== NULL && $customerCountryCode !== NULL && $customerPostCode !== NULL)
							{
								$cart = Mage::getSingleton('checkout/cart');
								$address = $cart->getQuote()->getShippingAddress();
								$address->setCountryId($customerCountryCode)
										->setPostcode($customerPostCode)
										->setCollectShippingrates(true);
								$rates = $address->collectShippingRates()->getGroupedAllShippingRates();
								$carrierArr = array();
								foreach ($rates as $carrier) {
									foreach ($carrier as $rate) {
										if(!in_array($rate->getData()['carrier_title'], $carrierArr)){
											array_push($carrierArr, $rate->getData()['carrier_title']);
											echo '</div><div class="shipping_scrollable" style="max-height:200px;border:1px;overflow:auto;">';
											echo '<br/><h3>'.$rate->getData()['carrier_title'].'</h3>';
										}
										$methodTitle = $rate->getData()['method_title'];
										$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
										$formattedPrice = $currencySymbol.number_format($rate->getData()['price'], 2, '.', ',');
										$customer_shippingmethod = $this->helper('accolade_bttn')->getShippingMethod($customerId);
										if($customer_shippingmethod == $rate->getData()['code']){
											echo '<input class="radio" type="radio" name="shipping_method" value='.$rate->getData()['code'].' checked />  '.$methodTitle.'  '.$formattedPrice.'<br/>'.'<br/><br/>';
										}
										else{
											echo '<input class="radio" type="radio" name="shipping_method" value='.$rate->getData()['code'].' />  '.$methodTitle.' '.$formattedPrice.'<br/>'.'<br/><br/>';
										}
									}
								}
							} else {
								echo '<br/><br/><h3>'.$this->__("Please add your address to the account.").'</h3>';
							}
							?>
						</li>
				</ul>
            </li>
        </ol>
    </div>

    <div class="col-2 addresses-primary">
        <ol>
		<h2><?php echo $this->__('Payment Method') ?></h2>
            <li class="item">
                <div class="fieldset">
					<ul class="form-list">
						<li>
							<label for="button_id"><?php echo $this->__('Choose default payment method:') ?></label>
							<br/><br/><br/>
							<?php
							   $payments = Mage::getSingleton('payment/config')->getActiveMethods();
							   $customer_paymentmethod = $this->helper('accolade_bttn')->getPaymentMethod($customerId);
							   foreach ($payments as $paymentCode=>$paymentModel) {
									$paymentTitle = Mage::getStoreConfig('payment/'.$paymentCode.'/title');
									if($paymentCode == $customer_paymentmethod){
										echo '<input class="radio" type="radio" name="payment_method" value='.$paymentCode.' checked />  '.$paymentTitle.'<br/><br/>';
									}
									else{
										echo '<input class="radio" type="radio" name="payment_method" value='.$paymentCode.' />  '.$paymentTitle.'<br/><br/>';
									}
								}
							?>
						</li>
					</ul>
				</div>
            </li>
        </ol>
		<button type="submit" title="<?php echo $this->__('Save') ?>" class="button f-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</div>
<br /><br />
</form>