<?php
$model = Mage::getModel('accolade_button/button');
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('My Button') ?></h1>
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Button')) ?>" class="button" onclick="window.location='<?php echo $this->getUrl('*/*/new') ?>';"><span><span><?php echo $this->__('Add New Button') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="col1-set buttons-list">
    <h2><?php echo $this->__('Associated Buttons') ?></h2>
    <ul>
        <?php $buttonsCollection = $model->getCustomerButtons();
        if ($buttonsCollection) :
            foreach ($buttonsCollection as $button) : ?>
                <li>
                    <span class="button-id">
                        <?php echo $button->getButtonId() ?>
                    </span>
                    <span class="button-links">
                        <a href="<?php echo $button->getEditUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__("Edit")) ?>"><?php echo $this->__("Edit") ?></a> |
                        <a href="<?php echo $button->getDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__("Delete")) ?>" class="button-delete"><?php echo $this->__("Delete") ?></a>
                    </span>
                </li>
            <?php endforeach;
        else : ?>
        <li>
            <?php echo $this->quoteEscape($this->__('You haven\'t added any buttons yet.')); ?>
        </li>
        <?php endif; ?>
    </ul>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this button?')) ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
