<div class="col-2 edit-bttn-settings">
	<ol>
	<h2><?php echo $this->__('Edit Bt.tn Settings') ?></h2>
		<label for="button_id" class="required"><?php echo $this->__('Edit Bt.tn settings') ?><em>*</em></label>
		<li class="item">
			<div class="fieldset">
				<ul class="form-list">
					<li>
						<br/>
						<label for="button_id" class="required"><?php echo $this->__('Bt.tn Device ID') ?><em>*</em></label>
						<div class="input-box">
							<input type="text" name="button_id" alt="button_id" id="button_id" class="input-text" value="<?php echo Mage::getSingleton('accolade_bttn/bttn')->getBttnId() ?>" required />
						</div>
					</li>
				</ul>
			</div>
		</li>
	</ol>
</div>