<?php $bttn= Mage::getSingleton('customer/session')->getBttn() ?>
<div class="col-2 order-template">
<ol>
	<h2><?php echo $this->__('Order Template') ?></h2>
	<li class="item">
		<div class="fieldset">
			<ul class="form-list">
				<li>
					<label for="button_id" class="required"><?php echo $this->__('Choose default order method') ?><em>*</em></label>
					<br/><br/>
					<table class="data-table">
						<col width="1" />
						<thead>
							<tr>
								<th><?php echo $this->__('Select') ?></th>
							</tr>
						</thead>
						<tbody>
							<td>
							<?php $orderMethod = $bttn->getOrderMethod() ?>
							<?php if ($orderMethod == 'wishlist'): ?>
								<?php echo str_repeat('&nbsp;', 5) ?>
								<input class="radio" type="radio" name="order_method" value="wishlist" checked required />
								<?php echo str_repeat('&nbsp;', 12).$this->__('Order Wishlist products') ?>
							<?php else: ?>
								<?php echo str_repeat('&nbsp;', 5) ?>
								<input class="radio" type="radio" name="order_method" value="wishlist" required />
								<?php echo str_repeat('&nbsp;', 12).$this->__('Order Wishlist products') ?>
							<?php endif; ?>
							</td>
						</tbody>
					</table>
					<div class="order_scrollable" style="max-height:500px;overflow:auto;">
					<?php $_orders = Mage::getModel('sales/order')->getCollection()->addFieldToFilter('customer_id', $bttn->getCustomerId())->addFieldToSelect('*')->addOrder('entity_id', 'desc') ?>
					<?php if ($_orders->getSize()): ?>
						<table class="data-table" id="my-orders-table" style="margin-top: 0px;">
							<col width="1" />
							<thead>
								<tr>
									<th><?php echo $this->__('Select') ?></th>
									<th><?php echo $this->__('Order #') ?></th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($_orders as $_order): ?>
								<tr>
									<td class="a-center">
									<?php $order_id = $_order->getRealOrderId() ?>
									<?php if($orderMethod == $order_id): ?>
										<input class="radio" type="radio" name="order_method" value="<?php echo $order_id ?>" style="margin-top: 6px;" checked required />
									<?php else: ?>
										<input class="radio" type="radio" name="order_method" value="<?php echo $order_id ?>" style="margin-top: 6px;" required />
									<?php endif; ?>
									</td>
									<td><?php echo $_order->getRealOrderId() ?></td>
									<td class="a-right">
										<span class="nobr">
											<a href="<?php echo $this->getUrl('sales/order/view', array('order_id' => $_order->getId()));?>" target="_blank"><?php echo $this->__('View Order') ?></a>
										</span>
									</td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					<?php endif; ?>
				</li>
			</ul>
		</div>
	</li>
</ol>
</div>
