<?php $bttn= Mage::getSingleton('customer/session')->getBttn() ?>

<div class="col-1 shipping-method" style="padding-left: 20px">
	<ol>
	<h2><?php echo $this->__('Shipping Method') ?></h2>
		<li class="item">
			<div class="fieldset">
				<ul class="form-list">
					<li>
						<label for="button_id" class="required"><?php echo $this->__('Choose default shipping method') ?><em>*</em></label><br/>
						<?php $checkShippingAddress = $bttn->getCheckShippingAddress() ?>
						<?php $orderMethod = $bttn->getOrderMethod() ?>
						<?php $isValid = $bttn->getCheckTemplate() ?>
						<?php if ($checkShippingAddress && $orderMethod != '' && $isValid == 1): ?>
							<?php $quote = Mage::getModel('sales/quote') ?>
							<?php $rates = $bttn->getTotals($quote, 'shipping') ?>
							<?php $carrierArr = array() ?>
							<?php foreach ($rates as $carrier): ?>
								<?php foreach ($carrier as $rate): ?>
									<?php if (!in_array($rate->getData()['carrier_title'], $carrierArr)): ?>
										<?php array_push($carrierArr, $rate->getData()['carrier_title']) ?>
										</div><div class="shipping_scrollable" style="max-height:200px;border:1px;overflow:auto;"><br/>
										<h3><?php echo $rate->getData()['carrier_title'] ?></h3>
									<?php endif; ?>
									<?php $methodTitle = $rate->getData()['method_title'] ?>
									<?php $formattedPrice = Mage::helper('core')->currency($rate->getData()['price'],true,false) ?>
									<?php $shippingMethod = $bttn->getShippingMethod() ?>
									<?php if ($shippingMethod == $rate->getData()['code']): ?>
										<input class="radio" type="radio" name="shipping_method" value="<?php echo $rate->getData()['code'] ?>" checked required />&nbsp;&nbsp;<?php echo $methodTitle.'  '.$formattedPrice ?><br/><br/><br/>
									<?php else: ?>
										<input class="radio" type="radio" name="shipping_method" value="<?php echo $rate->getData()['code'] ?>" required />&nbsp;&nbsp;<?php echo $methodTitle.'  '.$formattedPrice ?><br/><br/><br/>
									<?php endif; ?>
								<?php endforeach; ?>
							<?php endforeach; ?>
						<?php elseif ($isValid == 'wishlistHasConfigurable'): ?>
							<br/><br/><h3><?php echo $this->__('Wishlist contains product(s) with no required options') ?></h3>
						<?php elseif ($checkShippingAddress && $orderMethod == ''): ?>
							<br/><br/><h3><?php echo $this->__('Select your order template first') ?></h3>
						<?php elseif ($isValid == 0): ?>
							<br/><br/><h3><?php echo $this->__('Order template is empty') ?></h3>
						<?php else: ?>
							<br/><br/><h3><?php echo $this->__('Please add your address from the account settings') ?></h3>
						<?php endif; ?>
					</li>
				</ul>
		</li>
	</ol>
</div>
