<?php $button= Mage::getSingleton('customer/session')->getButton() ?>
<div class="col-1 payment-method">
    <ol>
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <li class="item">
            <div class="fieldset">
                <ul>
                    <li>
                        <label for="button_id" class="required"><?php echo $this->__('Choose default payment method') ?><em>*</em></label>
                    </li>
                        <?php $allowedMethods = explode(',', Mage::getStoreConfig('accolade/allowed_payment_methods/payment_methods')) ?>
                        <?php $payments = Mage::getSingleton('payment/config')->getActiveMethods() ?>
                        <?php $paymentMethod = $button->getPaymentMethod() ?>
                        <?php foreach ($payments as $paymentCode=>$paymentModel): ?>
                            <?php if (in_array($paymentCode, $allowedMethods)) : ?>
                                <li>
                                <?php $paymentTitle = Mage::getStoreConfig('payment/'.$paymentCode.'/title') ?>
                                <?php if ($paymentMethod == $paymentCode) : ?>
                                    <input class="radio" type="radio" name="payment_method" value="<?php echo $paymentCode ?>" checked required /><label><?php echo $paymentTitle ?></label>
                                <?php else: ?>
                                    <input class="radio" type="radio" name="payment_method" value="<?php echo $paymentCode ?>" required /><label><?php echo $paymentTitle ?></label>
                                <?php endif; ?>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </li>
                </ul>
            </div>
        </li>
    </ol>
</div>
